# Generated by Django 4.1.7 on 2023-03-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenmeProject', '0002_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.IntegerField()),
                ('loanPeriod', models.IntegerField()),
                ('annualRate', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('monthsPaid', models.IntegerField()),
                ('borrowerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenmeProject.borrower')),
                ('investorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lenmeProject.investor')),
            ],
        ),
    ]
