# Generated by Django 4.1.7 on 2023-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenmeProject', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='annualRate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='monthsPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
